name=MahbubQR
version=1.0.0
author=Mahbubul Islam
maintainer=Mahbubul Islam
sentence=QR Code Scanner Library for ESP32-S3 Camera
paragraph=A lightweight QR code scanning library for ESP32-S3 based camera boards
category=Signal Input/Output
url=
architectures=esp32